export const restaurantType = [
  "Fast food",
  "Café",
  "Bistrot/Bistro",
  "Pizzeria",
  "Steakhouse",
  "Sushi bar",
  "Gastronomique",
  "Brasserie",
  "Food truck",
  "Buffet",
  "Gastro-pub",
  "Restaurant végétarien/végan",
  "Restaurant à thème",
  "Dîner spectacle",
  "Restaurant de plage",
  "Rôtisserie",
  "Tapas bar",
  "Traiteur",
  "Restaurant itinérant",
  "Cantine",
  "Spécialité africaine",
  "Spécialité américaine",
  "Spécialité brésilienne",
  "Spécialité britannique",
  "Spécialité chinoise",
  "Spécialité coréenne",
  "Spécialité espagnole",
  "Spécialité française",
  "Spécialité grecque",
  "Spécialité indienne",
  "Spécialité italienne",
  "Spécialité japonaise",
  "Spécialité libanaise",
  "Spécialité marocaine",
  "Spécialité mexicaine",
  "Spécialité portugaise",
  "Spécialité russe",
  "Spécialité thaïlandaise",
  "Spécialité turque",
  "Spécialité vietnamienne",
]
export const type = ["Restaurant", "Musée", "Bar", "Parc"]
export const stars = [1, 2, 3]
export const price = [1, 2, 3, 4, 5]
export const isFree = ["Gratuit", "Payant"]
export const ArtisticCurrent = [
  "Abstrait",
  "Art déco",
  "Art nouveau",
  "Baroque",
  "Classicisme",
  "Cubisme",
  "Dadaïsme",
  "Expressionnisme",
  "Fauvisme",
  "Futurisme",
  "Gothique",
  "Impressionnisme",
  "Minimalisme",
  "Néo-classicisme",
  "Op art",
  "Pop art",
  "Réalisme",
  "Renaissance",
  "Rococo",
  "Romantisme",
  "Surréalisme",
  "Symbolisme",
]
export const typesOfArt = [
  "Architecture",
  "Art numérique",
  "Bande dessinée",
  "Calligraphie",
  "Céramique",
  "Cinéma",
  "Danse",
  "Dessin",
  "Graffiti",
  "Littérature",
  "Mode",
  "Musique",
  "Peinture",
  "Photographie",
  "Tapisserie",
  "Théâtre",
]
export const typeOfBar = [
  "Bar à bière",
  "Bar à cocktails",
  "Bar à vin",
  "Bar de plage",
  "Bar sportif",
  "Bar à whisky",
  "Pub",
  "Bar à tapas",
  "Bar karaoké",
  "Bar à jus",
  "Bar de glace",
  "Speakeasy",
  "Bar à shisha",
  "Bar de danse",
  "Bar à jeux",
  "Bar gay",
  "Bar à thème",
]
export const typeOfParc = [
  "Parc aquatique",
  "Parc d'aventure",
  "Parc animalier",
  "Parc d'attraction",
  "Parc botanique",
  "Parc d'État",
  "Parc de loisirs",
  "Parc de plage",
  "Parc de pocket",
  "Parc de sculptures",
  "Parc historique",
  "Parc linéaire",
  "Parc national",
  "Parc de skate",
  "Parc thématique",
  "Parc urbain",
  "Forêt urbaine",
  "Jardin japonais",
  "Jardin public",
  "Réserve naturelle",
]
export const isPrivate = ["Private", "Public"]

export const prices = [
  1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9.5, 10.5, 11,
  11.5, 12, 12.5, 13, 13.5, 14, 14.5, 15, 15.5, 16, 16.5, 17, 17.5, 18, 19,
  19.5, 20, 20.5, 21, 21.5, 22, 22.5, 23, 23.5, 24, 24.5, 25, 25.5, 26, 26.5,
  27.5, 28, 28.5, 29, 29.5, 30,
]
